
[project]
name = "muxtools"
version = "0.0.1"
description = "A library for various muxing and automation tools for anything and everything fansubbing related"
authors = [
    { name="Vodes", email="vodes.imp@gmail.com" }
]
dependencies = [
    "requests>=2.31.0",
    "fontcollector>=2.1.0",
    "ass>=0.5.3",
    "wget>=3.2",
    "py7zr>=0.20.5",
    "pymediainfo>=6.0.1",
    "rich>=13.1.0",
    "pyparsebluray>=0.1.4",
]
classifiers = [
    "Natural Language :: English",
    "Intended Audience :: Developers",
    "Intended Audience :: Other Audience",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Typing :: Typed",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Video :: Display",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MPL 2.0"}

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
"Source Code" = "https://github.com/Vodes/muxtools"
"Contact" = "https://discord.gg/Kf94Nv6WVN"

[project.scripts]
muxtools = "muxtools:entry_point"